### ISSUE TITLE
Listing Endpoints & Pageination

### ISSUE THREAD

**Issue by revol-xut** [tlm-solutions/datacare#12]
# Problem

We have too much stuff it doesn't fit on one page. 

# Suggestion 

Pagination for the frontend now the backend needs to know which part of the database is interesting for the user so we need to transfer `offset` and `limit` to the backend. 

**Talking API**

`GET /region&offset=20&limit=30`

Would now return 

```json
{
	"count": 300,
	"data": [ {}, {}, {} ] 
}
```

### Which Endpoints need to be touched ?

- `GET /region`
- `GET /station`
- `GET /user`

# Open Questions

- What should be the default behaviour when no offset or limit is specified?

**Comment by MarcelCoding** [comment]
idk offset = 0; limit = 30 - as defaults

**Comment by revol-xut** [comment]
sounds reasonable

**Comment by revol-xut** [comment]
Implemented with #13
