### ISSUE TITLE
API-Spec 

### ISSUE THREAD

**Issue by revol-xut** [tlm-solutions/datacare#2]
# Datacare API Specification 

## Open Question

- password reset ?
- where do we yeet leaderboards ?

### aut

- **POST /auth/login**
- **POST  /auth/logout**

### user
- **POST /user** (create) [all] 
- **GET /user** (list) [admin] 
- **PUT /user/id** (update) [admin, self] 
- **GET /user/id** (specific infos) [admin, self] 
	* returns a list of owned stations 
	* returns a list of trekkie runs
- **DELETE /user/id** (delete)  [admin, self] 
- **POST /user/id/trekkie** (trekkie runs valid)
- **DELETE /user/id/trekkie**  (trekkie runs invalid)

### region
- **GET /region** (list) [all] done #1
- **POST /region** (create) [admin]  done #1
- **GET /region/id** (specific) [all] done #1
	* returns a list of stations inside the region
- **PUT /region/id** (update) [admin] done #1
- **DELETE /region/id** (delete) [admin] done #1
- **GET /region/trekkie** (list of trekkie runs of region) [admin]

### stations
- **GET /station** (list) [all -> public, admin -> all]  done #3 
	* if the current user is admin it returns all stations otherwise only public ones
- **POST /station** (create) [authenticated] done #3
- **PUT /station/id** (update) [admin, self] done #3
- **GET /station/id** (specific infos) [all -> public, admin -> all] partially done #3
	* metrics like amount of telegrams received
	* metrics like average amount of telegrams per seconds
- **DELETE /station/id** (delete) [self, admin] done #3
- **POST /station/id/approve** (approving a station) [admin] done #3

### trekkie
=> creation is done by the trekkie service which also does file uploading but this service maybe should be integrated into datacare

- **GET /trekkie/run** (list) [self, admin]
- **PUT /trekkie/run** (update a run) [self, admin]
- **DELETE /trekkie/run** (delete) [self, admin]
- **GET /trekkie/gpx** (list gps files) [self, admin]
- **DELETE /trekkie/gpx** (delete gpx files) [self, admin]

**Comment by oxapentane** [comment]
I guess at this point this is implemented
