### ISSUE TITLE
Filter runs for treekie based on region identiefier

### ISSUE THREAD

**Issue by marenz2569** [tlm-solutions/datacare#30]
The current code is only matching line, run and time. This can lead to problems with the multiple regions.

https://github.com/tlm-solutions/datacare/blob/72eada20c4a6c1425f6ddbe30e25cf9fea351688/src/routes/trekkie/utils.rs#L51C1-L57C1

**Comment by tanneberger** [comment]
Yeah thats a problem but I think its an easy fix @marenz2569

**Comment by tanneberger** [comment]
@marenz2569 fixed
